//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 KML Ares-Operator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	commonv1 "github.com/kubeflow/common/pkg/apis/common/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AresJob) DeepCopyInto(out *AresJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AresJob.
func (in *AresJob) DeepCopy() *AresJob {
	if in == nil {
		return nil
	}
	out := new(AresJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AresJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AresJobList) DeepCopyInto(out *AresJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AresJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AresJobList.
func (in *AresJobList) DeepCopy() *AresJobList {
	if in == nil {
		return nil
	}
	out := new(AresJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AresJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AresJobSpec) DeepCopyInto(out *AresJobSpec) {
	*out = *in
	if in.TTLSecondsAfterFailed != nil {
		in, out := &in.TTLSecondsAfterFailed, &out.TTLSecondsAfterFailed
		*out = new(int32)
		**out = **in
	}
	in.RunPolicy.DeepCopyInto(&out.RunPolicy)
	if in.AvailablePorts != nil {
		in, out := &in.AvailablePorts, &out.AvailablePorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	in.Framework.DeepCopyInto(&out.Framework)
	if in.RoleSpecs != nil {
		in, out := &in.RoleSpecs, &out.RoleSpecs
		*out = make(map[commonv1.ReplicaType]*RoleSpec, len(*in))
		for key, val := range *in {
			var outVal *RoleSpec
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(RoleSpec)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.JobPhasePolicy != nil {
		in, out := &in.JobPhasePolicy, &out.JobPhasePolicy
		*out = new(JobPhasePolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AresJobSpec.
func (in *AresJobSpec) DeepCopy() *AresJobSpec {
	if in == nil {
		return nil
	}
	out := new(AresJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AresJobStatus) DeepCopyInto(out *AresJobStatus) {
	*out = *in
	if in.JobStatus != nil {
		in, out := &in.JobStatus, &out.JobStatus
		*out = new(commonv1.JobStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleStatuses != nil {
		in, out := &in.RoleStatuses, &out.RoleStatuses
		*out = make(map[commonv1.ReplicaType]*RoleStatus, len(*in))
		for key, val := range *in {
			var outVal *RoleStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(RoleStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.RunningTime != nil {
		in, out := &in.RunningTime, &out.RunningTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AresJobStatus.
func (in *AresJobStatus) DeepCopy() *AresJobStatus {
	if in == nil {
		return nil
	}
	out := new(AresJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaguaSpec) DeepCopyInto(out *BaguaSpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaguaSpec.
func (in *BaguaSpec) DeepCopy() *BaguaSpec {
	if in == nil {
		return nil
	}
	out := new(BaguaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependenceSpec) DeepCopyInto(out *DependenceSpec) {
	*out = *in
	if in.RoleNames != nil {
		in, out := &in.RoleNames, &out.RoleNames
		*out = make([]commonv1.ReplicaType, len(*in))
		copy(*out, *in)
	}
	if in.MPIHostFile != nil {
		in, out := &in.MPIHostFile, &out.MPIHostFile
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependenceSpec.
func (in *DependenceSpec) DeepCopy() *DependenceSpec {
	if in == nil {
		return nil
	}
	out := new(DependenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameworkSpec) DeepCopyInto(out *FrameworkSpec) {
	*out = *in
	if in.Bagua != nil {
		in, out := &in.Bagua, &out.Bagua
		*out = new(BaguaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MPI != nil {
		in, out := &in.MPI, &out.MPI
		*out = new(MPISpec)
		**out = **in
	}
	if in.Tensorflow != nil {
		in, out := &in.Tensorflow, &out.Tensorflow
		*out = new(TensorflowSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameworkSpec.
func (in *FrameworkSpec) DeepCopy() *FrameworkSpec {
	if in == nil {
		return nil
	}
	out := new(FrameworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobPhasePolicy) DeepCopyInto(out *JobPhasePolicy) {
	*out = *in
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = make([][]commonv1.ReplicaType, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]commonv1.ReplicaType, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.Succeeded != nil {
		in, out := &in.Succeeded, &out.Succeeded
		*out = make([][]commonv1.ReplicaType, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]commonv1.ReplicaType, len(*in))
				copy(*out, *in)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobPhasePolicy.
func (in *JobPhasePolicy) DeepCopy() *JobPhasePolicy {
	if in == nil {
		return nil
	}
	out := new(JobPhasePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPISpec) DeepCopyInto(out *MPISpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPISpec.
func (in *MPISpec) DeepCopy() *MPISpec {
	if in == nil {
		return nil
	}
	out := new(MPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaStatus) DeepCopyInto(out *ReplicaStatus) {
	*out = *in
	if in.ReplicaStatus != nil {
		in, out := &in.ReplicaStatus, &out.ReplicaStatus
		*out = new(commonv1.ReplicaStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaStatus.
func (in *ReplicaStatus) DeepCopy() *ReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolePhasePolicy) DeepCopyInto(out *RolePhasePolicy) {
	*out = *in
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = new(RolePhaseCondition)
		**out = **in
	}
	if in.Succeeded != nil {
		in, out := &in.Succeeded, &out.Succeeded
		*out = new(RolePhaseCondition)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolePhasePolicy.
func (in *RolePhasePolicy) DeepCopy() *RolePhasePolicy {
	if in == nil {
		return nil
	}
	out := new(RolePhasePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleSpec) DeepCopyInto(out *RoleSpec) {
	*out = *in
	if in.ReplicaSpec != nil {
		in, out := &in.ReplicaSpec, &out.ReplicaSpec
		*out = new(commonv1.ReplicaSpec)
		(*in).DeepCopyInto(*out)
	}
	in.RolePhasePolicy.DeepCopyInto(&out.RolePhasePolicy)
	if in.Dependence != nil {
		in, out := &in.Dependence, &out.Dependence
		*out = new(DependenceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleSpec.
func (in *RoleSpec) DeepCopy() *RoleSpec {
	if in == nil {
		return nil
	}
	out := new(RoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleStatus) DeepCopyInto(out *RoleStatus) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.ReplicaStatus.DeepCopyInto(&out.ReplicaStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleStatus.
func (in *RoleStatus) DeepCopy() *RoleStatus {
	if in == nil {
		return nil
	}
	out := new(RoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorflowSpec) DeepCopyInto(out *TensorflowSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorflowSpec.
func (in *TensorflowSpec) DeepCopy() *TensorflowSpec {
	if in == nil {
		return nil
	}
	out := new(TensorflowSpec)
	in.DeepCopyInto(out)
	return out
}
