# permissions for end users to view aresjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aresjob-viewer-role
rules:
- apiGroups:
  - ares.io
  resources:
  - aresjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ares.io
  resources:
  - aresjobs/status
  verbs:
  - get
