# permissions for end users to edit aresjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aresjob-editor-role
rules:
- apiGroups:
  - ares.io
  resources:
  - aresjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ares.io
  resources:
  - aresjobs/status
  verbs:
  - get
